[HWORKS-544] move featurestore search out of epipe
logicalclocks/ePipe pull request #89
Opened 2023-07-14 14:41 UTC by o-alex

2023-07-25 10:03 UTC, maismail requested changes
@o-alex can you open a PR on epipe-chef to update the version as part of this JIRA

2023-07-25 10:03 UTC, maismail commented on include/FileProvenanceConstants.h
>    inline Int64 getFeatureViewParentIId(Ndb* conn, INodeTable inodesTable, Int64 parentIId) {
Is this needed anywhere?

2023-07-25 10:03 UTC, maismail commented on include/FileProvenanceConstants.h
>    inline bool typeMLFeature(FileProvenanceRow row) {
is this still needed?

2023-08-28 12:49 UTC, o-alex commented on include/FileProvenanceConstants.h
>    inline Int64 getFeatureViewParentIId(Ndb* conn, INodeTable inodesTable, Int64 parentIId) {
removed

2023-08-28 12:50 UTC, o-alex commented on include/FileProvenanceConstants.h
>    inline bool typeMLFeature(FileProvenanceRow row) {
this one is still used by provenance

2023-08-28 13:50 UTC, maismail approved these changes

2023-08-29 13:34 UTC, merged